### ISSUE TITLE
convertTo('ttml') not working

### ISSUE THREAD

**Issue by mfallend** [captioning/captioning#41]
Hi,

I'm trying to convert SRT files to TTML but am only getting the following warning:

> Warning: get_class() expects parameter 1 to be object, string given in …/src/Captioning/Format/TtmlFile.php on line 114

I've also tried WebVTT as input format but keep getting the same warning.
Conversions to all other formats work without issue, only TTML doesn't work. :(

I'm using a slightly modified version of your example code:
```
<?php
 
require_once __DIR__ . '/vendor/autoload.php';

use Captioning\Format\SubripFile;
use Captioning\Format\TtmlFile;

try {
    $srt = new SubripFile('example-1.srt');
    echo $srt->convertTo('ttml')->build()->getFileContent();
    // $srt->convertTo('ttml')->save('test.dfxp');
} catch(Exception $e) {
    echo "Error: ".$e->getMessage()."\n";
}

?>
```

**Comment by delphiki** [comment]
I've checked the code and this is indeed related to the code, I'll fix it asap, thanks for the report!

**Comment by delphiki** [comment]
@mfallend It should be fixed now!

**Comment by mfallend** [comment]
Thanks for the fast change!
The error is gone but I'm still not getting any output for TTML.
All other formats show me proper output using
```
echo $srt->convertTo('webvtt')->build()->getFileContent();
echo $srt->convertTo('srt')->build()->getFileContent();
echo $srt->convertTo('json')->build()->getFileContent();
echo $srt->convertTo('sbv')->build()->getFileContent();
echo $srt->convertTo('substationalpha')->build()->getFileContent();
```

but `echo $srt->convertTo('ttml')->build()->getFileContent();` returns nothing

I've used the example-1.srt from the …tests/Fixtures folder and a custom SRT file.

**Comment by delphiki** [comment]
Actually the Ttml support is still a WIP.
As of now, you can only read a TTML file, but not render one, as you can see here: https://github.com/captioning/captioning/blob/master/src/Captioning/Format/TtmlFile.php#L102

I hope to find the time to implement it soon.

**Comment by mfallend** [comment]
Sorry, I completely missed that!

Thanks for the fast response time :)

**Comment by delphiki** [comment]
You're welcome, thanks for reminding me I forgot to implement it :)
